# site settings
title: R-Ladies Riverside
subtitle: 
email: riverside@rladies.org 
description: 
baseurl: "/r-ladies_test" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
meetup: https://www.meetup.com/rladies-riverside/

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
github_url: https://github.com/rladies/meetup-presentations_riverside
twitter_url: https://twitter.com/RLadiesRiversd

# build settings
markdown: kramdown

sass:
  style: compressed
