url: https://rladies.github.io/
baseurl: /riverside/

# Site settings
title: R-Ladies Riverside
email: riverside@rladies.org
description: "R-Ladies Riverside"

pages:
  - title: twitter
    url: https://twitter.com/RLadiesRiversd
  - title: github
    url: https://github.com/rladies/meetup-presentations_riverside

# Team names, titles and social links
people:
- name: Daniela Cassol
  pic: 1.png
  position: Co-Founder
  social:
    - title: twitter
      url: https://twitter.com/danicassol
    - title: github
      url: https://github.com/dcassol/

- name: Marília P. Gaiarsa
  pic: 2.png
  position: Co-Founder
  social:
    - title: twitter
      url: https://twitter.com/magaiarsa
    - title: github
      url: https://github.com/magaiarsa

- name: Teresa Bohner
  pic: 3.png
  position: Co-Founder
  social:
    - title: github
      url: https://github.com/tfbohner

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/RLadiesRiversd
  - title: github
    url: https://github.com/rladies/meetup-presentations_riverside

# Postal address (add as many lines as necessary)
# address:
#  - line: 
#  - line: 

# Build settings
markdown: kramdown
permalink: pretty